server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql://10.200.99.201:3306/pelican_harish?createDatabaseIfNotExist=true
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: #firstName in dto to first_name in db
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create